point_robot:  # Création des différents points pour former le robot
  p1:
    x: -150
    y: 50
  p2:
    x: 150
    y: 50
  p3:
    x: 150
    y: -50
  p4:
    x: 20
    y: -50
  p5:
    x: 20
    y: -150
  p6:
    x: -20
    y: -150
  p7: 
    x: -20
    y: -50
  p8:
    x: -150
    y: -50

# Défiition des capteurs
capteurs:
  ultrason1:
    type: ultrason
    x: 20 # position suivant x en mm
    y: 50 # position suivant y en mm
    theta: -40 #angle en degrès d'inclinaison du capteur par rapport au sens de marche du robot

  ultrason2:
    type: ultrason
    x: -20 # position suivant x en mm
    y: 50 # position suivant y en mm
    theta: 30 #angle en degrès

  ultrason3:
    type: ultrason
    x: -30 # position suivant x en mm
    y: -50 # position suivant y en mm
    theta: -190 #angle en degrès

  ultrason4:
    type: ultrason
    x: +30 # position suivant x en mm
    y: -50 # position suivant y en mm
    theta: 190 #angle en degrès

  ultrason5:
    type: ultrason
    x: 160 # position suivant x en mm
    y: 0 # position suivant y en mm
    theta: -90 #angle en degrès
