point_robot:  # Création des différents points pour former le robot
  p1:
    x: -135
    y: 92
  p2:
    x: 135
    y: 92
  p3:
    x: 135
    y: -28
  p4:
    x: 10
    y: -28
  p5:
    x: 10
    y: -92
  p6:
    x: -10
    y: -92
  p7: 
    x: -10
    y: -28
  p8:
    x: -135
    y: -28

# Défiition des capteurs
capteurs:
  ultrason1:
    type: ultrason
    x: 135 # position suivant x en mm
    y: 92 # position suivant y en mm
    theta: 0 #angle en degrès d'inclinaison du capteur par rapport au sens de marche du robot

  ultrason2:
    type: ultrason
    x: -135 # position suivant x en mm
    y: 92 # position suivant y en mm
    theta: 0 #angle en degrès


area_detection_obstacle:
  area_avant_gauche:
    p1:
      x: -400
      y: 400
    p2: 
      x: -300
      y: 0
    p3:
      x: -20
      y: 0
    p4: 
      x: -20
      y: 400

  area_avant_droite:
    p1:
      x: 400
      y: 400
    p2: 
      x: 300
      y: 0
    p3:
      x: 20
      y: 0
    p4: 
      x: 20
      y: 400

